import openai
openai.api_key = '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'
userInput = 'I want to go to somewhere summer, I want togo on safari and see wild animals. I am Moroccan, I dont want a destination that requires me a visa. I would d like to go aborad internationaly, Im okay with all cities & countries.' 
countries_list = 'Algeria; Benign; Bolivia; Brazil; Burkina Faso; Colombia; Ecuador; South Korea; Ivory Coast; Gabon; Gambia; Guinea Conakry; Hong Kong; Indonesia; Malaysia; Mali; Maldives; Niger; Philippines; Macau SAR; San Marino; São Tomé and Príncipe; Senegal; Tanzania; Tunisia; Turkey; Togo'
prompt = userInput + ' List of countries: ' + countries_list
completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
    {"role": "system", "content": "You will be used in a web application as a virtual travel assistant.. Users will type text as a prompt: 'I want to go to somewhere sunny this June, between 14 of 26th for less than 1000€. I want to relax and enjoy the sun but also do some ocean and water activities. I am Moroccan, I don't want a destination that requires me a visa. I'd like to go aborad internationaly, I'm okay with all cities & countries.' and a list of countries where they don't need visa to travel. for example:  'Algeria; Benign; Bolivia; Brazil; Burkina Faso; Colombia; Ecuador; South Korea; Ivory Coast; Gabon; Gambia; Guinea Conakry; Hong Kong; Indonesia; Malaysia; Mali; Maldives; Niger; Philippines; Macau SAR; San Marino; São Tomé and Príncipe; Senegal; Tanzania; Tunisia; Turkey; Togo' I will put their prompt in ChatGPT Api and I will programmatically retrieve chatGPT's reponse. For this to work, your reply must always an array of airports of the array of countries given to you. You will choose touristic countries in that list that also correspond to the user's input prompt and you will reply with an array of destination airports. You must not choose all countries, only appropriate choices. No explanations (since that would ruin my program) . You must only answer with a list of potential airport destinations, no talking, no explaning, nothing more or less. You must respect this format in all your replies: {'airports': ['x1', 'x2', 'x3']}. You must double check that thhe airports are exclusively from the list of countries given to you. You must only choose some countries. provide a response that only includes destinations within the list. provide a response that only respects requirements, rules of the prompts and destination. Starting from now. user input 'I want to go to somewhere summer, I want togo on safari and see wild animals. I am Moroccan, I don't want a destination that requires me a visa. I'd like to go aborad internationaly, I'm okay with all cities & countries.' List of countries: Algeria; Benign; Bolivia; Brazil; Burkina Faso; Colombia; Ecuador; South Korea; Ivory Coast; Gabon; Gambia; Guinea Conakry; Hong Kong; Indonesia; Malaysia; Mali; Maldives; Niger; Philippines; Macau SAR; San Marino; São Tomé and Príncipe; Senegal; Tanzania; Tunisia; Turkey; Togo"},
    {"role": "user",
               "content": prompt             }],
)
print(completion.get("choices")[0].get("message").get("content"))


